FROM python:3.11

RUN apt-get update && apt-get install -y \
    build-essential \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libx11-xcb1 \
    libxrender1 \
    libxkbcommon-x11-0 \
    qtbase5-dev \
    qtchooser \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/backend
COPY backend/ .
COPY data/ ./data

RUN pip install --no-cache-dir -r requirements.txt

#ENV PYTHONPATH=/app

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

