FROM python:3.11

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    build-essential \
    linux-libc-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/frontend

COPY frontend/ .
COPY data/ /app/frontend/data
COPY README.md ../README.md
COPY CONSIGNE.md /app
COPY images/ ./images
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
