version: '3.8'

services:
  # init-db:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend  # Ou chemin vers ton Dockerfile backend
  #   working_dir: /app/backend
  #   ports:
  #     - 8001:8001
  #   volumes:
  #     - ./backend:/app/backend
  #     - ./data:/app/backend/data
  #   depends_on: []
  #   restart: "no"
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    #working_dir: /app/backend
    ports:
      - "8000:8000"
    networks:
      - flix_network    
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    networks:
      - flix_network
      #
    # volumes:
    #   - ./data:/app/frontend/data:ro
    depends_on:
    - backend

networks:
  flix_network:
    driver: bridge
