version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - flix_network    
    #
    volumes:
      - ./data:/app/data  # Pour accéder à la BDD duckdb

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    networks:
      - flix_network
      #
    volumes:
      - ./data:/app/data  # Pour que Streamlit accède aussi à la BDD

networks:
  flix_network:
    driver: bridge
